defaults:
  - train_mix: s1_temp_0_6_top0p95        
  - labeler: semantic
  - prober: logistic
  - extractor: layer27_full
  - _self_                

run_mode: train
train_mode: crossdomain
model_name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
min_token_len: 10
seed: 41