model_name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
train_mix: 
  s1_temp_0_6_top0p95:
    ratio: 1
    temp: 0.6
    top_p: 0.95
    dataset_id: s1_temp_0_6_top0p95
    path: data/DeepSeek-R1-Distill-Qwen-7B_s1/results.json

override: true